name: Pester UnitTest on Ubuntu
on: push

permissions:
  checks: write
  pull-requests: write

jobs:
  pester-test:
    name: Pester test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Perform a Pester Tests
        if: always()
        run: |
          Invoke-Pester ./tests/*.ps1 -Passthru -OutputFile "./test-results/TestResults.xml" -OutputFormat NUnitXml

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            test-results/**/*.xml